# Generated by Django 4.2.19 on 2025-03-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
    ]
